[package]
name = "mnist"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.8.0", features = ["cuda"] }
